package org.data.Entity.JFinal.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfessor<M extends BaseProfessor<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}
	
	public void setCompany(java.lang.String Company) {
		set("Company", Company);
	}
	
	public java.lang.String getCompany() {
		return getStr("Company");
	}
	
	public void setDutyAndTitle(java.lang.String DutyAndTitle) {
		set("DutyAndTitle", DutyAndTitle);
	}
	
	public java.lang.String getDutyAndTitle() {
		return getStr("DutyAndTitle");
	}
	
	public void setProfessional(java.lang.String Professional) {
		set("Professional", Professional);
	}
	
	public java.lang.String getProfessional() {
		return getStr("Professional");
	}
	
	public void setPhone(java.lang.String Phone) {
		set("Phone", Phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("Phone");
	}
	
	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}
	
	public void setBankID(java.lang.String BankID) {
		set("BankID", BankID);
	}
	
	public java.lang.String getBankID() {
		return getStr("BankID");
	}
	
	public void setBank(java.lang.String Bank) {
		set("Bank", Bank);
	}
	
	public java.lang.String getBank() {
		return getStr("Bank");
	}
	
	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}
	
}

