package org.data.Entity.JFinal.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIecdept<M extends BaseIecdept<M>> extends Model<M> implements IBean {

	public void setTCorSC(java.lang.String TCorSC) {
		set("TCorSC", TCorSC);
	}
	
	public java.lang.String getTCorSC() {
		return getStr("TCorSC");
	}
	
	public void setPersonInCharge(java.lang.String PersonInCharge) {
		set("PersonInCharge", PersonInCharge);
	}
	
	public java.lang.String getPersonInCharge() {
		return getStr("PersonInCharge");
	}
	
	public void setEstablishedTime(java.lang.String establishedTime) {
		set("Established_time", establishedTime);
	}
	
	public java.lang.String getEstablishedTime() {
		return getStr("Established_time");
	}
	
	public void setTcorscTopicEn(java.lang.String tcorscTopicEn) {
		set("TCorSC_Topic_en", tcorscTopicEn);
	}
	
	public java.lang.String getTcorscTopicEn() {
		return getStr("TCorSC_Topic_en");
	}
	
	public void setTcorscTopicCn(java.lang.String tcorscTopicCn) {
		set("TCorSC_Topic_CN", tcorscTopicCn);
	}
	
	public java.lang.String getTcorscTopicCn() {
		return getStr("TCorSC_Topic_CN");
	}
	
	public void setProfessional(java.lang.String Professional) {
		set("Professional", Professional);
	}
	
	public java.lang.String getProfessional() {
		return getStr("Professional");
	}
	
	public void setSACorTC(java.lang.String SACorTC) {
		set("SACorTC", SACorTC);
	}
	
	public java.lang.String getSACorTC() {
		return getStr("SACorTC");
	}
	
	public void setDomesticStandardCommitment(java.lang.String domesticStandardCommitment) {
		set("domestic_standard_commitment", domesticStandardCommitment);
	}
	
	public java.lang.String getDomesticStandardCommitment() {
		return getStr("domestic_standard_commitment");
	}
	
	public void setContact(java.lang.String Contact) {
		set("Contact", Contact);
	}
	
	public java.lang.String getContact() {
		return getStr("Contact");
	}
	
	public void setTechniqueChargeCompany(java.lang.String techniqueChargeCompany) {
		set("Technique_charge_company", techniqueChargeCompany);
	}
	
	public java.lang.String getTechniqueChargeCompany() {
		return getStr("Technique_charge_company");
	}
	
	public void setPhone(java.lang.String Phone) {
		set("Phone", Phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("Phone");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
}

