package org.data.Entity.JFinal.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStandardenergy<M extends BaseStandardenergy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 标准名称
	 */
	public void setStdName(java.lang.String stdName) {
		set("std_name", stdName);
	}
	
	/**
	 * 标准名称
	 */
	public java.lang.String getStdName() {
		return getStr("std_name");
	}
	
	/**
	 * 标准标号
	 */
	public void setStdCode(java.lang.String stdCode) {
		set("std_code", stdCode);
	}
	
	/**
	 * 标准标号
	 */
	public java.lang.String getStdCode() {
		return getStr("std_code");
	}
	
	/**
	 * 编制状态
	 */
	public void setStdEditStatus(java.lang.String stdEditStatus) {
		set("std_edit_status", stdEditStatus);
	}
	
	/**
	 * 编制状态
	 */
	public java.lang.String getStdEditStatus() {
		return getStr("std_edit_status");
	}
	
	/**
	 * 备注(国标、行标..)
	 */
	public void setStdCategory(java.lang.String stdCategory) {
		set("std_category", stdCategory);
	}
	
	/**
	 * 备注(国标、行标..)
	 */
	public java.lang.String getStdCategory() {
		return getStr("std_category");
	}
	
	/**
	 * 归类(设计、施工..)
	 */
	public void setStdSystem(java.lang.String stdSystem) {
		set("std_system", stdSystem);
	}
	
	/**
	 * 归类(设计、施工..)
	 */
	public java.lang.String getStdSystem() {
		return getStr("std_system");
	}
	
	/**
	 * 更新状态
	 */
	public void setStdUpdate(java.lang.String stdUpdate) {
		set("std_update", stdUpdate);
	}
	
	/**
	 * 更新状态
	 */
	public java.lang.String getStdUpdate() {
		return getStr("std_update");
	}
	
	/**
	 * 发布部门
	 */
	public void setStdPublishDept(java.lang.String stdPublishDept) {
		set("std_publish_dept", stdPublishDept);
	}
	
	/**
	 * 发布部门
	 */
	public java.lang.String getStdPublishDept() {
		return getStr("std_publish_dept");
	}
	
	/**
	 * 提出单位
	 */
	public void setStdIdeaDept(java.lang.String stdIdeaDept) {
		set("std_idea_dept", stdIdeaDept);
	}
	
	/**
	 * 提出单位
	 */
	public java.lang.String getStdIdeaDept() {
		return getStr("std_idea_dept");
	}
	
	/**
	 * 归口单位
	 */
	public void setStdTechniqueCommitment(java.lang.String stdTechniqueCommitment) {
		set("std_technique_commitment", stdTechniqueCommitment);
	}
	
	/**
	 * 归口单位
	 */
	public java.lang.String getStdTechniqueCommitment() {
		return getStr("std_technique_commitment");
	}
	
	/**
	 * 主管部门
	 */
	public void setStdAdminDept(java.lang.String stdAdminDept) {
		set("std_admin_dept", stdAdminDept);
	}
	
	/**
	 * 主管部门
	 */
	public java.lang.String getStdAdminDept() {
		return getStr("std_admin_dept");
	}
	
	/**
	 * 主编部门
	 */
	public void setStdMainEditDept(java.lang.String stdMainEditDept) {
		set("std_main_edit_dept", stdMainEditDept);
	}
	
	/**
	 * 主编部门
	 */
	public java.lang.String getStdMainEditDept() {
		return getStr("std_main_edit_dept");
	}
	
	/**
	 * 批准部门
	 */
	public void setStdAuthorizerDept(java.lang.String stdAuthorizerDept) {
		set("std_authorizer_dept", stdAuthorizerDept);
	}
	
	/**
	 * 批准部门
	 */
	public java.lang.String getStdAuthorizerDept() {
		return getStr("std_authorizer_dept");
	}
	
	/**
	 * 主编单位
	 */
	public void setStdMainEditCompany(java.lang.String stdMainEditCompany) {
		set("std_main_edit_company", stdMainEditCompany);
	}
	
	/**
	 * 主编单位
	 */
	public java.lang.String getStdMainEditCompany() {
		return getStr("std_main_edit_company");
	}
	
	/**
	 * 参编单位
	 */
	public void setStdParticipateEditCompany(java.lang.String stdParticipateEditCompany) {
		set("std_participate_edit_company", stdParticipateEditCompany);
	}
	
	/**
	 * 参编单位
	 */
	public java.lang.String getStdParticipateEditCompany() {
		return getStr("std_participate_edit_company");
	}
	
}

