package org.data.Entity.JFinal;

import org.data.Entity.JFinal.base.BaseStandardenergy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Standardenergy extends BaseStandardenergy<Standardenergy> {
	
}

