package org.data.Entity.JFinal;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("iecdept", "TCorSC", Iecdept.class);
		arp.addMapping("professor", "Name", Professor.class);
		arp.addMapping("standardenergy", "id", Standardenergy.class);
		arp.addMapping("standardenergyupdate", "id", Standardenergyupdate.class);
	}
}


