package org.data.Entity.JFinal;

import org.data.Entity.JFinal.base.BaseProfessor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Professor extends BaseProfessor<Professor> {
	
}

