package org.data.Entity.JFinal;

import org.data.Entity.JFinal.base.BaseStandardenergyupdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Standardenergyupdate extends BaseStandardenergyupdate<Standardenergyupdate> {
	
}

