package org.data.Entity.JFinal.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import io.vproxy.vfx.ui.table.CellAware;
import io.vproxy.vfx.ui.table.RowInformer;
import io.vproxy.vfx.ui.table.RowInformerAware;
import javafx.scene.Node;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStandardenergyupdate<M extends BaseStandardenergyupdate<M>> extends Model<M> implements IBean, RowInformerAware, CellAware<BaseStandardenergyupdate> {


	private RowInformer informer;
	public void setId(Integer id) {
		set("id", id);
		informer.informRowUpdate();
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 归类(设计、施工..)
	 */
	public void setStdSystemId(String stdSystemId) {
		set("std_system_id", stdSystemId);

		informer.informRowUpdate();
	}
	
	/**
	 * 归类(设计、施工..)
	 */
	public String getStdSystemId() {
		return getStr("std_system_id");
	}
	
	public void setStdSystemName(String stdSystemName) {
		set("std_system_name", stdSystemName);
		informer.informRowUpdate();
	}
	
	public String getStdSystemName() {
		return getStr("std_system_name");

	}
	
	/**
	 * 标准名称
	 */
	public void setStdName(String stdName) {
		set("std_name", stdName);
		informer.informRowUpdate();
	}
	
	/**
	 * 标准名称
	 */
	public String getStdName() {
		return getStr("std_name");
	}
	
	/**
	 * 标准标号
	 */
	public void setStdCode(String stdCode) {
		set("std_code", stdCode);
		informer.informRowUpdate();
	}
	
	/**
	 * 标准标号
	 */
	public String getStdCode() {
		return getStr("std_code");
	}

	/**
	 * 编制状态
	 */
	public void setStdEditStatus(String stdEditStatus) {
		set("std_edit_status", stdEditStatus);
		informer.informRowUpdate();
	}
	
	/**
	 * 编制状态
	 */
	public String getStdEditStatus() {
		return getStr("std_edit_status");
	}
	
	/**
	 * 备注(国标、行标..)
	 */
	public void setStdCategory(String stdCategory) {
		set("std_category", stdCategory);
		informer.informRowUpdate();
	}
	
	/**
	 * 备注(国标、行标..)
	 */
	public String getStdCategory() {
		return getStr("std_category");
	}
	
	/**
	 * 更新状态
	 */
	public void setStdUpdate(String stdUpdate) {
		set("std_update", stdUpdate);
		informer.informRowUpdate();
	}
	
	/**
	 * 更新状态
	 */
	public String getStdUpdate() {
		return getStr("std_update");
	}
	
	/**
	 * 发布部门
	 */
	public void setStdPublishDept(String stdPublishDept) {
		set("std_publish_dept", stdPublishDept);
		informer.informRowUpdate();
	}
	
	/**
	 * 发布部门
	 */
	public String getStdPublishDept() {
		return getStr("std_publish_dept");
	}
	
	/**
	 * 提出单位
	 */
	public void setStdIdeaDept(String stdIdeaDept) {
		set("std_idea_dept", stdIdeaDept);
		informer.informRowUpdate();
	}
	
	/**
	 * 提出单位
	 */
	public String getStdIdeaDept() {
		return getStr("std_idea_dept");
	}
	
	/**
	 * 归口单位
	 */
	public void setStdTechniqueCommitment(String stdTechniqueCommitment) {
		set("std_technique_commitment", stdTechniqueCommitment);
		informer.informRowUpdate();
	}
	
	/**
	 * 归口单位
	 */
	public String getStdTechniqueCommitment() {
		return getStr("std_technique_commitment");
	}
	
	/**
	 * 主管部门
	 */
	public void setStdAdminDept(String stdAdminDept) {
		set("std_admin_dept", stdAdminDept);
		informer.informRowUpdate();
	}
	
	/**
	 * 主管部门
	 */
	public String getStdAdminDept() {
		return getStr("std_admin_dept");
	}
	
	/**
	 * 主编部门
	 */
	public void setStdMainEditDept(String stdMainEditDept) {
		set("std_main_edit_dept", stdMainEditDept);
		informer.informRowUpdate();
	}
	
	/**
	 * 主编部门
	 */
	public String getStdMainEditDept() {
		return getStr("std_main_edit_dept");
	}
	
	/**
	 * 批准部门
	 */
	public void setStdAuthorizerDept(String stdAuthorizerDept) {
		set("std_authorizer_dept", stdAuthorizerDept);
		informer.informRowUpdate();
	}
	
	/**
	 * 批准部门
	 */
	public String getStdAuthorizerDept() {
		return getStr("std_authorizer_dept");
	}
	
	/**
	 * 主编单位
	 */
	public void setStdMainEditCompany(String stdMainEditCompany) {
		set("std_main_edit_company", stdMainEditCompany);
		informer.informRowUpdate();
	}
	
	/**
	 * 主编单位
	 */
	public String getStdMainEditCompany() {
		return getStr("std_main_edit_company");
	}
	
	/**
	 * 参编单位
	 */
	public void setStdParticipateEditCompany(String stdParticipateEditCompany) {
		set("std_participate_edit_company", stdParticipateEditCompany);
		informer.informRowUpdate();
	}
	
	/**
	 * 参编单位
	 */
	public String getStdParticipateEditCompany() {
		return getStr("std_participate_edit_company");
	}
	
}

